
#-----------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------

# Version a utiliser pour le format du fichier docker-compose
version: "3"

services :

  # CONTAINER - mariadb :
  # https://hub.docker.com/_/mariadb
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp

  # CONTAINER - WORDPRESS :
  # https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    container_name: wp_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - /mnt/stockage/wordpress:/var/www/html
      - /mnt/stockage/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "6060:443"
    networks:
      - wp

  # CONTAINER - Bitnami/Dokuwiki :
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    container_name: wiki
    restart: always
    ports:
      - "4343:443"
    volumes:
      - '/mnt/stockage/dokuwiki_data:/bitnami'
    environment:
      DOCKER_CONTENT_TRUST: 1
      DOKUWIKI_USERNAME: 'daniel'
      DOKUWIKI_FULL_NAME: 'dos santos'
      DOKUWIKI_PASSWORD: 'password'
      DOKUWIKI_EMAIL: 'danielitto91@gmail.com'
      DOKUWIKI_WIKI_NAME: 'Super Wiki'
      PHP_MEMORY_LIMIT: '2000M'
    networks:
      - wp

networks:
  wp:
