
#-----------------------------------------------------------------------------------
# Ressources :
# https://docs.docker.com/compose/compose-file/#image
# https://docs.docker.com/compose/compose-file/#restart
# https://docs.docker.com/compose/compose-file/#volumes
# https://docs.docker.com/compose/compose-file/#environment
#-----------------------------------------------------------------------------------

# Version a utiliser pour le format du fichier docker-compose
version: "3"

services :

  # CONTAINER - mariadb :
  # https://hub.docker.com/_/mariadb
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp

  # CONTAINER - WORDPRESS :
  # https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wp_wordpress
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "80:80"
    networks:
      - wp

  # CONTAINER - dokuwikitos :
  # à build ...
  dokuwiki:
    image: dokuwikitos
    container_name: wiki
    restart: always
    ports:
      - "8080:80"
    networks:
      - wp

networks:
  wp:

volumes:
  db_data:
